const INFO = "INFO";
const INFO_WITHOUT_OK = "INFO_WITHOUT_OK";

const WARNING = "WARNING";
const LOADING = "LOADING";
const INVALID_LOGIN = "INVALID_LOGIN";
const VIEW_DEV_CON_REQUEST = "VIEW_DEV_CON_REQUEST";
const VIEW_DEV_CON_DETAILS = "VIEW_DEV_CON_DETAILS";
const VIEW_LD_ACCESS_URL = "VIEW_LD_ACCESS_URL";
const VIEW_OPEN_API = "VIEW_OPEN_API";
const VIEW_DENIAL_REASON = "VIEW_DENIAL_REASON";
const VIEW_COMPLETE_REQUEST = "VIEW_COMPLETE_REQUEST";
const SETTING_UP_ENVIRONMENT="SETTING_UP_ENVIROMENT";
const OPEN_API_SELECTION_OPTIONS_DEV="OPEN_API_SELECTION_OPTIONS_DEV";
export default {
  INFO,
  WARNING,
  LOADING,
  INVALID_LOGIN,
  VIEW_DEV_CON_REQUEST,
  VIEW_DEV_CON_DETAILS,
  VIEW_COMPLETE_REQUEST,
  INFO_WITHOUT_OK,
  SETTING_UP_ENVIRONMENT,
  OPEN_API_SELECTION_OPTIONS_DEV,
  VIEW_LD_ACCESS_URL,
  VIEW_OPEN_API,
  VIEW_DENIAL_REASON
};
