const INFO = "INFO";
const WARNING = "WARNING";
const LOADING = "LOADING";
const INVALID_LOGIN = "INVALID_LOGIN";
const VIEW_DEV_CON_REQUEST = "VIEW_DEV_CON_REQUEST";
const VIEW_DEV_CON_DETAILS = "VIEW_DEV_CON_DETAILS";
const VIEW_DENIAL_REASON = "VIEW_DENIAL_REASON";
const VIEW_COMPLETE_REQUEST = "VIEW_COMPLETE_REQUEST";

export default {
  INFO,
  WARNING,
  LOADING,
  INVALID_LOGIN,
  VIEW_DEV_CON_REQUEST,
  VIEW_DEV_CON_DETAILS,
  VIEW_COMPLETE_REQUEST,
};
